server:
  port: 8085
spring:
  application:
    name: checkout-service
  data:
    redis:
      host: redis
      port: 6379
kafka:
  bootstrap-servers: kafka:29092
management:
  endpoints:
    web:
      exposure:
        include: "*"
