server:
  port: 8081
spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://postgres-catalog:5432/catalog
    username: catalog
    password: catalog
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
management:
  endpoints:
    web:
      exposure:
        include: "*"
