server:
  port: 8084
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://postgres-inventory:5432/inventorydb
    username: inventory
    password: inventory
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
kafka:
  bootstrap-servers: kafka:29092
management:
  endpoints:
    web:
      exposure:
        include: "*"
